version: 'version 1.0.0'
services:
  web:
    image: ...
    build: ./web-app
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - mongonetwork
  mlc:
    image: ...
    build: ./machine-learning-client
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    networks:
      - mongonetwork

  mongodb:
    image: ...
    build: ./database
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - mongonetwork
volumes:
  mongodata:

networks:
  mongonetwork:
    #driver: bridge