version: '3.10'
services:
  web:
    image: jladrover/emotion_tracker:web-app
    build: ./web-app
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - mongonetwork
  mlc:
    image: jladrover/emotion_tracker:client
    build: ./machine-learning-client
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    networks:
      - mongonetwork

  mongodb:
    image: jladrover/emotion_tracker:mongo
    build: ./database
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - mongonetwork
volumes:
  mongodata:

networks:
  mongonetwork:
    #driver: bridge