version: 'version 1.0.0'
services:
  web:
    build: ./web-app
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - mongonetwork
  mlc:
    build: ./machine-learning-client

  mongodb:

volumes:
  mongodata:

networks:
  mongonetwork:
    #driver: bridge