name: Web App (CI/CD)

on:
  pull_request:
    types: [closed]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install
        cd web-app

    - name: Run tests
      run: |
        pipenv run pytest

    # - name: Docker hub login
    #   uses:
    #   with:
    #     username: $ {{ secrets.DOCKER_USERNAME }}
    #     password: $ {{ secrets.DOCKER_PASSWORD }}

    # - name: Deploy
    #   run: |
    #     # Replace this with your deployment commands
    #     echo "Deploying application"